// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmTkvM3GMPGZrsQ9mbNDXouard7eCclU',
    appId: '1:44983026062:web:e9c9fe72298920c682a4df',
    messagingSenderId: '44983026062',
    projectId: 'final-project-d95a1',
    authDomain: 'final-project-d95a1.firebaseapp.com',
    storageBucket: 'final-project-d95a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3DBvxSx4UTVLrBsvP7842jilyRv7KPo',
    appId: '1:44983026062:android:958a1dd8e5965ac182a4df',
    messagingSenderId: '44983026062',
    projectId: 'final-project-d95a1',
    storageBucket: 'final-project-d95a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8TCNhjvhr1auEhC2xTKrAA0XWVVa7zVo',
    appId: '1:44983026062:ios:ffe5337be5c008df82a4df',
    messagingSenderId: '44983026062',
    projectId: 'final-project-d95a1',
    storageBucket: 'final-project-d95a1.appspot.com',
    androidClientId: '44983026062-il44ckts441jkrg627bsb32ovcsgit7t.apps.googleusercontent.com',
    iosClientId: '44983026062-h3a022h40qq0pugqu9rmv5qmucc82tgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
